# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Montevideo', max_length=120)),
                ('guia_de_transito', models.DecimalField(decimal_places=2, default=6, max_digits=10)),
                ('timbre_profesional', models.DecimalField(decimal_places=2, default=6, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=4, default=0.02, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=4, default=0.22, max_digits=10)),
                ('anticipo_iva', models.DecimalField(decimal_places=4, default=0.1, max_digits=10)),
                ('cert_empadronamiento', models.DecimalField(decimal_places=2, default=15, max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Itau', max_length=120)),
                ('transfer_out_local', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('transfer_in_local', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('transfer_out_international', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('commission_usd_eur', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agency R.', max_length=120)),
                ('plane', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('train', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('car', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('phone', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('dhl', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
                ('various', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mercyl', max_length=120)),
                ('car', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('nafta_maquina', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('phone', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('mercado_libre', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('work', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('various', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraordinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Escala 1', max_length=120)),
                ('cif_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cif_up', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fix_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='contadora', max_length=120)),
                ('annual', models.DecimalField(decimal_places=2, default=5124, max_digits=10)),
                ('currency', models.CharField(default='UYU', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Full Cargo', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despachante', models.CharField(default='Navatta', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=90, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Escala 1', max_length=120)),
                ('despachante', models.CharField(default='Navatta', max_length=120)),
                ('cif_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cif_up', models.DecimalField(decimal_places=2, default=25000, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=4, default=1.5, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mevas', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KMA', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='retroexcavadora', max_length=120)),
                ('brand', models.CharField(default='Case', max_length=120)),
                ('model', models.CharField(default='580 SLE', max_length=120)),
                ('length', models.DecimalField(decimal_places=2, default=5.56, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, default=2.29, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=3.8, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=8.0, max_digits=10)),
                ('comment', models.CharField(default='', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Escala 1', max_length=120)),
                ('ratio_low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ratio_up', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('multiplicator', models.DecimalField(decimal_places=2, default=13, max_digits=6)),
                ('ley_de_estiba', models.DecimalField(decimal_places=2, default=0.25, max_digits=6)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Denmark', max_length=120)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('tax', models.DecimalField(decimal_places=2, default=375, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='taxes', max_length=120)),
                ('irae', models.DecimalField(decimal_places=2, default=0.25, max_digits=10)),
                ('dividend', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('currency', models.CharField(default='UYU', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Soccar Shipping Agency', max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, default=440, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Anvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Escala 1', max_length=120)),
                ('cif_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cif_up', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=4, default=0.2, max_digits=10)),
                ('fix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
